/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'CmdMsg'
 * message type.
 */

public class CmdMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 6;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = -1;

    /** Create a new CmdMsg of size 6. */
    public CmdMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new CmdMsg of the given data_length. */
    public CmdMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg with the given data_length
     * and base offset.
     */
    public CmdMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg using the given byte array
     * as backing store.
     */
    public CmdMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public CmdMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public CmdMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg embedded in the given message
     * at the given base offset.
     */
    public CmdMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg embedded in the given message
     * at the given base offset and length.
     */
    public CmdMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <CmdMsg> \n";
      try {
        s += "  [dests=0x"+Long.toHexString(get_dests())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sender=0x"+Long.toHexString(get_sender())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [seqno=0x"+Long.toHexString(get_seqno())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [instr=0x"+Long.toHexString(get_instr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: dests
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'dests' is signed (false).
     */
    public static boolean isSigned_dests() {
        return false;
    }

    /**
     * Return whether the field 'dests' is an array (false).
     */
    public static boolean isArray_dests() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'dests'
     */
    public static int offset_dests() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'dests'
     */
    public static int offsetBits_dests() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'dests'
     */
    public int get_dests() {
        return (int)getUIntBEElement(offsetBits_dests(), 16);
    }

    /**
     * Set the value of the field 'dests'
     */
    public void set_dests(int value) {
        setUIntBEElement(offsetBits_dests(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'dests'
     */
    public static int size_dests() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'dests'
     */
    public static int sizeBits_dests() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sender
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sender' is signed (false).
     */
    public static boolean isSigned_sender() {
        return false;
    }

    /**
     * Return whether the field 'sender' is an array (false).
     */
    public static boolean isArray_sender() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sender'
     */
    public static int offset_sender() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sender'
     */
    public static int offsetBits_sender() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'sender'
     */
    public int get_sender() {
        return (int)getUIntBEElement(offsetBits_sender(), 16);
    }

    /**
     * Set the value of the field 'sender'
     */
    public void set_sender(int value) {
        setUIntBEElement(offsetBits_sender(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sender'
     */
    public static int size_sender() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sender'
     */
    public static int sizeBits_sender() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: seqno
    //   Field type: short, unsigned
    //   Offset (bits): 32
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'seqno' is signed (false).
     */
    public static boolean isSigned_seqno() {
        return false;
    }

    /**
     * Return whether the field 'seqno' is an array (false).
     */
    public static boolean isArray_seqno() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'seqno'
     */
    public static int offset_seqno() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'seqno'
     */
    public static int offsetBits_seqno() {
        return 32;
    }

    /**
     * Return the value (as a short) of the field 'seqno'
     */
    public short get_seqno() {
        return (short)getUIntBEElement(offsetBits_seqno(), 8);
    }

    /**
     * Set the value of the field 'seqno'
     */
    public void set_seqno(short value) {
        setUIntBEElement(offsetBits_seqno(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'seqno'
     */
    public static int size_seqno() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'seqno'
     */
    public static int sizeBits_seqno() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: instr
    //   Field type: short, unsigned
    //   Offset (bits): 40
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'instr' is signed (false).
     */
    public static boolean isSigned_instr() {
        return false;
    }

    /**
     * Return whether the field 'instr' is an array (false).
     */
    public static boolean isArray_instr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'instr'
     */
    public static int offset_instr() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'instr'
     */
    public static int offsetBits_instr() {
        return 40;
    }

    /**
     * Return the value (as a short) of the field 'instr'
     */
    public short get_instr() {
        return (short)getUIntBEElement(offsetBits_instr(), 8);
    }

    /**
     * Set the value of the field 'instr'
     */
    public void set_instr(short value) {
        setUIntBEElement(offsetBits_instr(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'instr'
     */
    public static int size_instr() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'instr'
     */
    public static int sizeBits_instr() {
        return 8;
    }

}
