COMPONENT=ThreadAppC
# This is the group of communication
# including directly python2.6 because no better way in sim.extra was found to change the include PATH
CFLAGS+=-DCC2420_NO_ACKNOWLEDGEMENTS
CFLAGS+=-DCC2420_NO_ADDRESS_RECOGNITION
CFLAGS+=-DTOSH_DATA_LENGTH=115

include $(MAKERULES)
