/**
 * @author Kevin Klues <klueska@cs.stanford.edu>
 */

#ifndef BASE_STATION_APP_STACK_H
#define BASE_STATION_APP_STACK_H

enum {
  BOOT_THREAD_STACK_SIZE            = 200,
  RADIO_RECEIVE_THREAD_STACK_SIZE   = 200,
  RADIO_SNOOP_THREAD_STACK_SIZE     = 200,
  SERIAL_SEND_THREAD_STACK_SIZE     = 200,
  SERIAL_RECEIVE_THREAD_STACK_SIZE  = 200,
  RADIO_SEND_THREAD_STACK_SIZE      = 200,
};

#endif //BASE_STATION_APP_STACK_H
